# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

controlled_stepper__ctor <- function(type, eps_abs, eps_rel) {
    .Call('rodeint_controlled_stepper__ctor', PACKAGE = 'rodeint', type, eps_abs, eps_rel)
}

controlled_stepper__type <- function(s) {
    .Call('rodeint_controlled_stepper__type', PACKAGE = 'rodeint', s)
}

integrate <- function(target, y, t0, t1, dt) {
    .Call('rodeint_integrate', PACKAGE = 'rodeint', target, y, t0, t1, dt)
}

integrate_observed <- function(target, y, t0, t1, dt) {
    .Call('rodeint_integrate_observed', PACKAGE = 'rodeint', target, y, t0, t1, dt)
}

integrate_adaptive <- function(stepper, target, y, t0, t1, dt, with_info = FALSE) {
    .Call('rodeint_r_integrate_adaptive', PACKAGE = 'rodeint', stepper, target, y, t0, t1, dt, with_info)
}

target_r__ctor <- function(derivs, pars_type) {
    .Call('rodeint_target_r__ctor', PACKAGE = 'rodeint', derivs, pars_type)
}

target_r__derivs <- function(target, y, t) {
    .Call('rodeint_target_r__derivs', PACKAGE = 'rodeint', target, y, t)
}

target_r__set_pars <- function(target, pars) {
    invisible(.Call('rodeint_target_r__set_pars', PACKAGE = 'rodeint', target, pars))
}

