# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

r_integrate_simple <- function(target, y, t0, t1, dt, save_state = FALSE) {
    .Call('rodeint_r_integrate_simple', PACKAGE = 'rodeint', target, y, t0, t1, dt, save_state)
}

r_integrate_const <- function(stepper, target, y, t0, t1, dt, save_state) {
    .Call('rodeint_r_integrate_const', PACKAGE = 'rodeint', stepper, target, y, t0, t1, dt, save_state)
}

r_integrate_n_steps <- function(stepper, target, y, t0, dt, n, save_state) {
    .Call('rodeint_r_integrate_n_steps', PACKAGE = 'rodeint', stepper, target, y, t0, dt, n, save_state)
}

r_integrate_adaptive <- function(stepper, target, y, t0, t1, dt, save_state = FALSE) {
    .Call('rodeint_r_integrate_adaptive', PACKAGE = 'rodeint', stepper, target, y, t0, t1, dt, save_state)
}

r_integrate_times <- function(stepper, target, y, times, dt) {
    .Call('rodeint_r_integrate_times', PACKAGE = 'rodeint', stepper, target, y, times, dt)
}

stepper_basic__ctor <- function(type) {
    .Call('rodeint_stepper_basic__ctor', PACKAGE = 'rodeint', type)
}

stepper_basic__type <- function(s) {
    .Call('rodeint_stepper_basic__type', PACKAGE = 'rodeint', s)
}

stepper_controlled__ctor <- function(type, eps_abs, eps_rel) {
    .Call('rodeint_stepper_controlled__ctor', PACKAGE = 'rodeint', type, eps_abs, eps_rel)
}

stepper_controlled__type <- function(s) {
    .Call('rodeint_stepper_controlled__type', PACKAGE = 'rodeint', s)
}

stepper__ctor <- function(type, subtype, eps_abs, eps_rel) {
    .Call('rodeint_stepper__ctor', PACKAGE = 'rodeint', type, subtype, eps_abs, eps_rel)
}

stepper__type <- function(s) {
    .Call('rodeint_stepper__type', PACKAGE = 'rodeint', s)
}

target_cpp__derivs <- function(target, y, t) {
    .Call('rodeint_target_cpp__derivs', PACKAGE = 'rodeint', target, y, t)
}

target_cpp__get_pars <- function(target) {
    .Call('rodeint_target_cpp__get_pars', PACKAGE = 'rodeint', target)
}

target_cpp__set_pars <- function(target, pars) {
    invisible(.Call('rodeint_target_cpp__set_pars', PACKAGE = 'rodeint', target, pars))
}

target_r__ctor <- function(derivs, pars_type) {
    .Call('rodeint_target_r__ctor', PACKAGE = 'rodeint', derivs, pars_type)
}

target_r__derivs <- function(target, y, t) {
    .Call('rodeint_target_r__derivs', PACKAGE = 'rodeint', target, y, t)
}

target_r__get_pars <- function(target) {
    .Call('rodeint_target_r__get_pars', PACKAGE = 'rodeint', target)
}

target_r__set_pars <- function(target, pars) {
    invisible(.Call('rodeint_target_r__set_pars', PACKAGE = 'rodeint', target, pars))
}

test_harmonic_oscillator <- function() {
    .Call('rodeint_test_harmonic_oscillator', PACKAGE = 'rodeint')
}

